Repository kang123077/Mars-to-Earth, pull requests merged in 2023-04, with the labels that each got.

#30 26 projectile system
  MarstoEarth/Assets/Animations/Miles/Animations/Jump.fbx.meta
  MarstoEarth/Assets/Animations/Miles/Animators/SciFiWarrior.controller
  MarstoEarth/Assets/Prefabs/HPCharacter.prefab
  MarstoEarth/Assets/Prefabs/Item/Cube.prefab
  MarstoEarth/Assets/Prefabs/Item/Cube.prefab.meta
  MarstoEarth/Assets/Resources/SkillsStat.meta
  MarstoEarth/Assets/Resources/SkillsStat/SmashStat.asset
  MarstoEarth/Assets/Resources/SkillsStat/SmashStat.asset.meta
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scripts/Character/Character.cs
  MarstoEarth/Assets/Scripts/Character/M_CR_42.cs
  MarstoEarth/Assets/Scripts/Character/Monster.cs
  MarstoEarth/Assets/Scripts/Character/Player.cs
  MarstoEarth/Assets/Scripts/ResourceManager.cs
  MarstoEarth/Assets/Scripts/Skill/Projectile.cs
  MarstoEarth/Assets/Scripts/Skill/Projectile.cs.meta
  MarstoEarth/Assets/Scripts/Skill/SPC.cs
  MarstoEarth/Assets/Scripts/Skill/Skill.cs
  MarstoEarth/Assets/Scripts/Skill/SkillInfo.cs
  MarstoEarth/Assets/Scripts/Skill/SkillInfo.cs.meta
  MarstoEarth/Assets/Scripts/Skill/Smash.cs
  MarstoEarth/Assets/Scripts/Skill/Smash.cs.meta
  MarstoEarth/Assets/Scripts/SpawnManager.cs
  MarstoEarth/ProjectSettings/TagManager.asset
Labels: System Structure

#31 Feature/8 map node making system2
  MarstoEarth/.editorconfig
  MarstoEarth/Assets/Prefabs/Map.meta
  MarstoEarth/Assets/Prefabs/Map/Node.meta
  MarstoEarth/Assets/Prefabs/Map/Node/NodePrefabTest.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/NodePrefabTest.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/PathPrefabTest.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/PathPrefabTest.prefab.meta
  MarstoEarth/Assets/Scenes/MapTestScenes.unity
  MarstoEarth/Assets/Scenes/MapTestScenes.unity.meta
  MarstoEarth/Assets/Scripts/Generators.meta
  MarstoEarth/Assets/Scripts/Generators/MapGenerator.cs
  MarstoEarth/Assets/Scripts/Generators/MapGenerator.cs.meta
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs.meta
  MarstoEarth/Assets/Scripts/Infos.meta
  MarstoEarth/Assets/Scripts/Infos/MapInfo.cs
  MarstoEarth/Assets/Scripts/Infos/MapInfo.cs.meta
  MarstoEarth/Assets/Scripts/Infos/NodeInfo.cs
  MarstoEarth/Assets/Scripts/Infos/NodeInfo.cs.meta
  MarstoEarth/Assets/Scripts/Infos/StageInfo.cs
  MarstoEarth/Assets/Scripts/Infos/StageInfo.cs.meta
  MarstoEarth/Assets/Scripts/Infos/TestDungeonInfo.cs
  MarstoEarth/Assets/Scripts/Infos/TestDungeonInfo.cs.meta
  MarstoEarth/Assets/Scripts/Managers.meta
  MarstoEarth/Assets/Scripts/MapManager.cs
Labels: System Structure, Refactor

#52 Feature/50 map event develop
  MarstoEarth/Assets/Animations/Gate/CloseGate.anim
  MarstoEarth/Assets/Animations/Gate/OpenGate.anim
  MarstoEarth/Assets/MapAssets/SpeedTutor - Tutorial Scene - FREE/Material/M_Tileable_Cube.mat
  MarstoEarth/Assets/MapAssets/SpeedTutor - Tutorial Scene - FREE/Material/M_Tileable_Walls.mat
  MarstoEarth/Assets/Prefabs/HPCharacter.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52.meta
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodePlane52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodePlane52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodeWall52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodeWall52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestPathGate52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestPathGate52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/TestNodeFloorC52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/TestNodeFloorC52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/TestNodeFloorW.prefab
  MarstoEarth/Assets/Scenes/MapPrefabScene.unity
  MarstoEarth/Assets/Scenes/NodeEditScene.unity
  MarstoEarth/Assets/Scenes/NodeEditScene/NavMesh.asset
  MarstoEarth/Assets/Scenes/NodeEditScene/NavMesh.asset.meta
  MarstoEarth/Assets/Scripts/Character/Player.cs
  MarstoEarth/Assets/Scripts/Controller/CameraController.cs
  MarstoEarth/Assets/Scripts/Controller/GateController.cs
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Managers/MapManager.cs
Labels: enhancement, Refactor

#54 20230412 Develop Pull Request
  MarstoEarth/Assets/Animations/Gate/CloseGate.anim
  MarstoEarth/Assets/Animations/Gate/OpenGate.anim
  MarstoEarth/Assets/Animations/Miles/Animators/SciFiWarrior.controller
  MarstoEarth/Assets/MapAssets/SpeedTutor - Tutorial Scene - FREE/Material/M_Tileable_Cube.mat
  MarstoEarth/Assets/MapAssets/SpeedTutor - Tutorial Scene - FREE/Material/M_Tileable_Walls.mat
  MarstoEarth/Assets/Prefabs/Cr-42.prefab
  MarstoEarth/Assets/Prefabs/HPCharacter.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52.meta
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodePlane52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodePlane52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodeWall52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodeWall52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestPathGate52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestPathGate52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/TestNodeFloorC52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/TestNodeFloorC52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/Node/TestNodeFloorW.prefab
  MarstoEarth/Assets/Prefabs/ProjectileMeshs/Cube.prefab
  MarstoEarth/Assets/Prefabs/ProjectileMeshs/projectileSlot.prefab
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scenes/MapPrefabScene.unity
  MarstoEarth/Assets/Scenes/NodeEditScene.unity
  MarstoEarth/Assets/Scenes/NodeEditScene/NavMesh.asset
  MarstoEarth/Assets/Scenes/NodeEditScene/NavMesh.asset.meta
  MarstoEarth/Assets/Scripts/Character/Character.cs
  MarstoEarth/Assets/Scripts/Character/M_CR_42.cs
  MarstoEarth/Assets/Scripts/Character/Player.cs
  MarstoEarth/Assets/Scripts/Controller/CameraController.cs
  MarstoEarth/Assets/Scripts/Controller/GateController.cs
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Managers/MapManager.cs
  MarstoEarth/Assets/Scripts/Projectile/GravityEffect.cs
  MarstoEarth/Assets/Scripts/Projectile/Projectile.cs
  MarstoEarth/Assets/Scripts/Skill/ChargeShotSkill.cs
  MarstoEarth/Assets/Scripts/Skill/DistortionSkill.cs
  MarstoEarth/Assets/Scripts/Skill/MassShootingSkill.cs
Labels: enhancement, System Structure, Refactor, Module Structure

#59 Feature/57 monster spawn event
  MarstoEarth/Assets/Animations/Gate/CloseGate.anim
  MarstoEarth/Assets/Animations/Gate/OpenGate.anim
  MarstoEarth/Assets/Prefabs/HPCharacter.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodePlane52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestPathGate52.prefab
  MarstoEarth/Assets/Scenes/NodeEditScene.unity
  MarstoEarth/Assets/Scripts/Character/Monster.cs
  MarstoEarth/Assets/Scripts/Controller/GateController.cs
  MarstoEarth/Assets/Scripts/Controller/NodeController.cs
  MarstoEarth/Assets/Scripts/Controller/NodeController.cs.meta
  MarstoEarth/Assets/Scripts/Controller/PathController.cs
  MarstoEarth/Assets/Scripts/Controller/PathController.cs.meta
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Infos/NodeInfo.cs
  MarstoEarth/Assets/Scripts/Managers/MapManager.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
Labels: enhancement, Module Structure

#71 Develop
  MarstoEarth/Assets/Animations/M_CR42/CR42animator.controller
  MarstoEarth/Assets/Animations/M_CR42/CR43animator.controller
  MarstoEarth/Assets/Animations/M_CR42/CR44animator.controller
  MarstoEarth/Assets/Animations/M_CR42/X Bot@Gunplay.fbx
  MarstoEarth/Assets/Animations/M_CR42/X Bot@Gunplay.fbx.meta
  MarstoEarth/Assets/Animations/M_Titan/TitanAnimator Controller.controller
  MarstoEarth/Assets/Animations/Miles/Animations/Reload.fbx.meta
  MarstoEarth/Assets/Animations/Miles/Animators/SciFiWarrior.controller
  MarstoEarth/Assets/Animations/Monster_kamikaze/Animation/robotSphereAnmCont.controller
  MarstoEarth/Assets/CinemachineManager.cs
  MarstoEarth/Assets/CinemachineManager.cs.meta
  MarstoEarth/Assets/CustomLockCameraY.cs
  MarstoEarth/Assets/CustomLockCameraY.cs.meta
  MarstoEarth/Assets/New Terrain.asset
  MarstoEarth/Assets/New Terrain.asset.meta
  MarstoEarth/Assets/Prefabs/HPCharacter.prefab
  MarstoEarth/Assets/Prefabs/Kamikaze.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodePlane52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestPathGate52.prefab
  MarstoEarth/Assets/Resources/CharactersStat/Miles.asset
  MarstoEarth/Assets/Resources/SkillsStat/Bite.asset
  MarstoEarth/Assets/Resources/SkillsStat/Block.asset
  MarstoEarth/Assets/Resources/SkillsStat/Charge.asset
  MarstoEarth/Assets/Resources/SkillsStat/Charge.asset.meta
  MarstoEarth/Assets/Resources/SkillsStat/ChargeShot.asset
  MarstoEarth/Assets/Resources/SkillsStat/Distortion.asset
  MarstoEarth/Assets/Resources/Sprites/aim.png
  MarstoEarth/Assets/Resources/Sprites/aim.png.meta
  MarstoEarth/Assets/Resources/Sprites/aim2.png
  MarstoEarth/Assets/Resources/Sprites/aim2.png.meta
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scripts/Character/CR_0.cs
  MarstoEarth/Assets/Scripts/Character/Character.cs
  MarstoEarth/Assets/Scripts/Character/M_Kamikaze.cs
  MarstoEarth/Assets/Scripts/Character/Monster.cs
  MarstoEarth/Assets/Scripts/Character/PlagueDoctor.cs
  MarstoEarth/Assets/Scripts/Character/Player.cs
  MarstoEarth/Assets/Scripts/Character/Titan.cs
  MarstoEarth/Assets/Scripts/Controller/CameraController.cs
  MarstoEarth/Assets/Scripts/Managers/ResourceManager.cs
  MarstoEarth/Assets/Scripts/Managers/SingleTon.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
  MarstoEarth/Assets/Scripts/Skill/BlockSkill.cs
  MarstoEarth/Assets/Scripts/Skill/ChargeShotSkill.cs
  MarstoEarth/Assets/Scripts/Skill/ChargeShotSkill.cs.meta
  MarstoEarth/Assets/Scripts/Skill/ChargeSkill.cs
  MarstoEarth/Assets/Scripts/Skill/ChargeSkill.cs.meta
  MarstoEarth/Assets/Scripts/Skill/DistortionSkill.cs
  MarstoEarth/Assets/Scripts/Skill/ParringKick.cs
  MarstoEarth/Assets/Scripts/Skill/RollSkill.cs
Labels: enhancement, Refactor, Module Structure

#73 Develop
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestNodePlane52.prefab
  MarstoEarth/Assets/Prefabs/Map/Node/Size52/TestPathGate52.prefab
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scripts/Controller/GateController.cs
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
  MarstoEarth/Assets/Scripts/Managers/UIManager.cs
  MarstoEarth/ProjectSettings/TagManager.asset
Labels: bug, enhancement
