Repository kang123077/Mars-to-Earth, pull requests merged in 2023-06, with the labels that each got.

#190 173 visual update with cardui and aim
  MarstoEarth/Assets/Animations/Card/ReinforceCardUI.anim
  MarstoEarth/Assets/MobileSettingUI.cs
  MarstoEarth/Assets/MobileSettingUI.cs.meta
  MarstoEarth/Assets/Resources/Sprites/AlphaHp.png
  MarstoEarth/Assets/Resources/Sprites/AlphaHp.png.meta
  MarstoEarth/Assets/Resources/Sprites/battery.png
  MarstoEarth/Assets/Resources/Sprites/battery.png.meta
  MarstoEarth/Assets/Resources/Sprites/full.png
  MarstoEarth/Assets/Resources/Sprites/full.png.meta
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scenes/LoadingScene.unity
  MarstoEarth/Assets/Scenes/OutGameScene.unity
  MarstoEarth/Assets/Scripts/Managers/OutGameUIManager.cs
  MarstoEarth/Assets/Scripts/Managers/UIManager.cs
  MarstoEarth/Assets/Scripts/OutGames/ButtonHovers.cs
  MarstoEarth/Assets/Scripts/OutGames/OutGameMobileSetting.cs
  MarstoEarth/Assets/Scripts/OutGames/OutGameMobileSetting.cs.meta
  MarstoEarth/Assets/Scripts/OutGames/OutGameSettingUI.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardHover.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardInfo.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardUIControll.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/ReinforceInfo.cs
  MarstoEarth/Assets/Scripts/UI/InGame/Combat/CombatUI.cs
Labels: enhancement

#197 Feature/192 static pause system
  MarstoEarth/Assets/Resources/CharactersStat/CR_0.asset
  MarstoEarth/Assets/Resources/CharactersStat/M_Titan.asset
  MarstoEarth/Assets/Scripts/Controllers/UIControllers/GameoverUIController.cs
  MarstoEarth/Assets/Scripts/Controllers/UIControllers/StageClearUIController.cs
  MarstoEarth/Assets/Scripts/Infos/MapInfo.cs
  MarstoEarth/Assets/Scripts/Managers/InGameManager.cs
  MarstoEarth/Assets/Scripts/Managers/OutGameUIManager.cs
  MarstoEarth/Assets/Scripts/Managers/UIManager.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardUIControll.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/ReinforceInfo.cs
  MarstoEarth/Assets/Scripts/UI/InGame/Combat/CombatUI.cs
  MarstoEarth/Assets/Scripts/UI/Setting/MobileSettingUI.cs
  MarstoEarth/Assets/Scripts/UI/Setting/SettingUI.cs
Labels: enhancement, System Structure

#198 196 settings synchronization
  MarstoEarth/Assets/Resources/CharactersStat/Miles.asset
  MarstoEarth/Assets/Scripts/Managers/OutGameUIManager.cs
  MarstoEarth/Assets/Scripts/OutGames/OutGameSettingUI.cs
  MarstoEarth/Assets/Scripts/UI/Setting/MobileSettingUI.cs
  MarstoEarth/Assets/Scripts/UI/Setting/SettingUI.cs
Labels: enhancement

#200 Develop
  MarstoEarth/Assets/Animations/Monster_kamikaze/Animation/robotSphereAnmCont.controller
  MarstoEarth/Assets/PolygonParticleFX/Prefabs/FX_BloodSplat_01.prefab
  MarstoEarth/Assets/Prefabs/Monsters/Cr-Ball.prefab
  MarstoEarth/Assets/Prefabs/Monsters/Cr-Ball.prefab.meta
  MarstoEarth/Assets/Resources/CharactersStat/CR_0.asset
  MarstoEarth/Assets/Resources/CharactersStat/M_CR_Ball.asset
  MarstoEarth/Assets/Resources/CharactersStat/M_CR_Ball.asset.meta
  MarstoEarth/Assets/Resources/CharactersStat/M_Titan.asset
  MarstoEarth/Assets/Resources/SkillsStat/AegisBarrier.asset
  MarstoEarth/Assets/Resources/SkillsStat/AirRaid.asset
  MarstoEarth/Assets/Resources/SkillsStat/AirRaid.asset.meta
  MarstoEarth/Assets/Resources/SkillsStat/Bite.asset
  MarstoEarth/Assets/Resources/SkillsStat/Charge.asset
  MarstoEarth/Assets/Resources/SkillsStat/Distortion.asset
  MarstoEarth/Assets/Resources/SkillsStat/Gardian.asset
  MarstoEarth/Assets/Resources/SkillsStat/GravityBomb.asset
  MarstoEarth/Assets/Resources/SkillsStat/Grenade.asset
  MarstoEarth/Assets/Resources/SkillsStat/MassShooting.asset
  MarstoEarth/Assets/Resources/SkillsStat/SpiderMine.asset
  MarstoEarth/Assets/Resources/SkillsStat/StimPack.asset
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/airRaid.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/airRaid.png.meta
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/overclocking.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/overclocking.png.meta
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/superdrug.png
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scenes/LoadingScene.unity
  MarstoEarth/Assets/Scenes/OutGameScene.unity
  MarstoEarth/Assets/Scripts/Character/Character.cs
  MarstoEarth/Assets/Scripts/Character/M_CR_Ball.cs
  MarstoEarth/Assets/Scripts/Character/M_CR_Ball.cs.meta
  MarstoEarth/Assets/Scripts/Character/Player.cs
  MarstoEarth/Assets/Scripts/Character/StatInfo.cs
  MarstoEarth/Assets/Scripts/Character/Titan.cs
  MarstoEarth/Assets/Scripts/Controllers/UIControllers/GameoverUIController.cs
  MarstoEarth/Assets/Scripts/Controllers/UIControllers/StageClearUIController.cs
  MarstoEarth/Assets/Scripts/Infos/MapInfo.cs
  MarstoEarth/Assets/Scripts/Item/Item.cs
  MarstoEarth/Assets/Scripts/Managers/InGameManager.cs
  MarstoEarth/Assets/Scripts/Managers/OutGameUIManager.cs
  MarstoEarth/Assets/Scripts/Managers/UIManager.cs
  MarstoEarth/Assets/Scripts/OutGames/OutGameSettingUI.cs
  MarstoEarth/Assets/Scripts/Skill/RollSkill.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardUIControll.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/ReinforceInfo.cs
  MarstoEarth/Assets/Scripts/UI/InGame/Combat/CombatUI.cs
  MarstoEarth/Assets/Scripts/UI/InGame/Combat/JoyStick.cs
  MarstoEarth/Assets/Scripts/UI/OutGame/CameraResolution.cs
  MarstoEarth/Assets/Scripts/UI/Setting/MobileSettingUI.cs
  MarstoEarth/Assets/Scripts/UI/Setting/SettingUI.cs
Labels: enhancement

#216 Feature/214 mobile level design
  MarstoEarth/Assets/Resources/SkillsStat/OverClock.asset
  MarstoEarth/Assets/Scripts/Character/Monster.cs
  MarstoEarth/Assets/Scripts/Character/Player.cs
  MarstoEarth/Assets/Scripts/Item/Item.cs
  MarstoEarth/Assets/Scripts/Skill/StimPackSkill.cs
Labels: enhancement

#221 Feature/220 sub issues
  MarstoEarth/Assets/Prefabs/Characters/HPCharacter.prefab
  MarstoEarth/Assets/Prefabs/Map/TestNodes/TestPathGate52.prefab
  MarstoEarth/Assets/Resources/Fonts/Silver.asset
  MarstoEarth/Assets/Resources/Fonts/Silver.asset.meta
  MarstoEarth/Assets/Resources/Fonts/Silver.ttf
  MarstoEarth/Assets/Resources/Fonts/Silver.ttf.meta
  MarstoEarth/Assets/Resources/SkillsStat/AirRaid.asset
  MarstoEarth/Assets/Resources/SkillsStat/Block.asset
  MarstoEarth/Assets/Resources/SkillsStat/Boomerang.asset
  MarstoEarth/Assets/Resources/SkillsStat/Charge.asset
  MarstoEarth/Assets/Resources/SkillsStat/Distortion.asset
  MarstoEarth/Assets/Resources/SkillsStat/Gardian.asset
  MarstoEarth/Assets/Resources/SkillsStat/GravityBomb.asset
  MarstoEarth/Assets/Resources/SkillsStat/Grenade.asset
  MarstoEarth/Assets/Resources/SkillsStat/MassShooting.asset
  MarstoEarth/Assets/Resources/SkillsStat/SpiderMine.asset
  MarstoEarth/Assets/Resources/Sprites/Icons/PlayerForwardIcon.png
  MarstoEarth/Assets/Resources/Sprites/Icons/PlayerForwardIcon.png.meta
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scripts/Controllers/LightController.cs
  MarstoEarth/Assets/Scripts/Controllers/LightController.cs.meta
  MarstoEarth/Assets/Scripts/Controllers/Path/GateController.cs
  MarstoEarth/Assets/Scripts/Managers/MapManager.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
  MarstoEarth/Assets/Scripts/Skill/BlockSkill.cs
  MarstoEarth/Assets/Scripts/Skill/BoomerangSkill.cs
  MarstoEarth/Assets/Scripts/Skill/GardianSkill.cs
  MarstoEarth/Assets/Scripts/Skill/GravityBombSkill.cs
  MarstoEarth/Assets/Scripts/Skill/GrenadeSkill.cs
  MarstoEarth/Assets/Scripts/Skill/HyperionSkill.cs
  MarstoEarth/Assets/Scripts/Skill/MassShootingSkill.cs
  MarstoEarth/Assets/Scripts/Skill/SpiderMineSkill.cs
Labels: bug, enhancement

#224 Add : Alert Icon
  MarstoEarth/Assets/Prefabs/Characters/HPCharacter.prefab
  MarstoEarth/Assets/Prefabs/Map/Rock/YellowRockPlaneBaked.prefab
  MarstoEarth/Assets/Prefabs/Map/SFRoom/BakedSFRoom_01 2.prefab
  MarstoEarth/Assets/Prefabs/Map/SFWarehouse/SFWarehouse_00.prefab
  MarstoEarth/Assets/Prefabs/Map/TestNodes/TestNodePlane52.prefab
  MarstoEarth/Assets/Resources/SkillsStat/MassShooting.asset
  MarstoEarth/Assets/Resources/Sprites/Icons/AlertIcon.png
  MarstoEarth/Assets/Resources/Sprites/Icons/AlertIcon.png.meta
  MarstoEarth/Assets/Resources/Sprites/Icons/DangerIcon.png
  MarstoEarth/Assets/Resources/Sprites/Icons/DangerIcon.png.meta
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Infos/NodeInfo.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
Labels: bug, enhancement

#225 Add : EnemyNum Increase
  MarstoEarth/Assets/Scripts/Controllers/UIControllers/GameInfoUIController.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
Labels: enhancement

#231 Feature/229 map camera path
  MarstoEarth/Assets/Prefabs/Map/SFRoom/BakedSFRoom_01 2.prefab
  MarstoEarth/Assets/Prefabs/Map/TestNodes/TestPathGate52.prefab
  MarstoEarth/Assets/Resources/SkillsStat/AegisBarrier.asset
  MarstoEarth/Assets/Resources/SkillsStat/AirRaid.asset
  MarstoEarth/Assets/Resources/SkillsStat/Block.asset
  MarstoEarth/Assets/Resources/SkillsStat/Boomerang.asset
  MarstoEarth/Assets/Resources/SkillsStat/Charge.asset
  MarstoEarth/Assets/Resources/SkillsStat/Distortion.asset
  MarstoEarth/Assets/Resources/SkillsStat/Gardian.asset
  MarstoEarth/Assets/Resources/SkillsStat/GravityBomb.asset
  MarstoEarth/Assets/Resources/SkillsStat/Grenade.asset
  MarstoEarth/Assets/Resources/SkillsStat/MassShooting.asset
  MarstoEarth/Assets/Resources/SkillsStat/OverClock.asset
  MarstoEarth/Assets/Resources/SkillsStat/Roll.asset
  MarstoEarth/Assets/Resources/SkillsStat/Smash.asset
  MarstoEarth/Assets/Resources/SkillsStat/SpiderMine.asset
  MarstoEarth/Assets/Scripts/Character/Player.cs
  MarstoEarth/Assets/Scripts/Controllers/Path/GateController.cs
  MarstoEarth/Assets/Scripts/Controllers/Path/PathController.cs
Labels: bug, enhancement
