Repository kang123077/Mars-to-Earth, pull requests merged in 2023-05, with the labels that each got.

#109 20230505 Develop PR
  MarstoEarth/Assets/Prefabs/Monsters/Cr-0.prefab
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scripts/Managers/ResourceManager.cs
  MarstoEarth/Assets/Scripts/Skill/BiteSkill.cs
  MarstoEarth/Assets/Scripts/Skill/BlockSkill.cs
  MarstoEarth/Assets/Scripts/Skill/SkillInfo.cs
  MarstoEarth/Assets/Scripts/Skill/SmashSkill.cs
  MarstoEarth/Assets/Scripts/UI/InGame/Combat/SkillSlot.cs
Labels: enhancement

#113 Feature/96 map variation 2
  MarstoEarth/Assets/MapAssets/_Creepy_Cat/_3D Scifi Kit Starter Kit/_Meshes/Materials/Wall_Atlas_01_Dif.mat
  MarstoEarth/Assets/MapAssets/_Creepy_Cat/_3D Showroom Free/_Meshes/Materials/Hard_Surface_01_Alpha.mat
  MarstoEarth/Assets/MapAssets/_Creepy_Cat/_3D Showroom Free/_Meshes/Materials/Hard_Surface_01_Grey_A.mat
  MarstoEarth/Assets/Materials/New Lighting Settings.lighting
  MarstoEarth/Assets/Materials/New Lighting Settings.lighting.meta
  MarstoEarth/Assets/Prefabs/Map/SFRoom/BakedSFRoom_01 2.prefab
  MarstoEarth/Assets/Prefabs/Map/TestNodes/BakedGate52.prefab
  MarstoEarth/Assets/Prefabs/Map/TestNodes/BakedGate52.prefab.meta
  MarstoEarth/Assets/Prefabs/Map/TestNodes/TestPathGate52.prefab
  MarstoEarth/Assets/Prefabs/Monsters/Cr-0.prefab
  MarstoEarth/Assets/Prefabs/Monsters/Cr-42.prefab
  MarstoEarth/Assets/Prefabs/Monsters/Titan.prefab
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scenes/InGameSceneLM.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM.unity
  MarstoEarth/Assets/Scenes/InGameSceneLM/LightingData.asset
  MarstoEarth/Assets/Scenes/InGameSceneLM/LightingData.asset.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-0_comp_dir.png
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-0_comp_dir.png.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-0_comp_light.exr
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-0_comp_light.exr.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-1_comp_dir.png
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-1_comp_dir.png.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-1_comp_light.exr
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-1_comp_light.exr.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-2_comp_dir.png
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-2_comp_dir.png.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-2_comp_light.exr
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-2_comp_light.exr.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-3_comp_dir.png
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-3_comp_dir.png.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-3_comp_light.exr
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-3_comp_light.exr.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-4_comp_dir.png
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-4_comp_dir.png.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-4_comp_light.exr
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-4_comp_light.exr.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-5_comp_dir.png
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-5_comp_dir.png.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-5_comp_light.exr
  MarstoEarth/Assets/Scenes/InGameSceneLM/Lightmap-5_comp_light.exr.meta
  MarstoEarth/Assets/Scenes/InGameSceneLM/ReflectionProbe-0.exr
  MarstoEarth/Assets/Scenes/InGameSceneLM/ReflectionProbe-0.exr.meta
  MarstoEarth/Assets/Scripts/Character/Player.cs
  MarstoEarth/Assets/Scripts/Controller/Path/OuterController.cs
  MarstoEarth/Assets/Scripts/Controller/Path/PathController.cs
Labels: enhancement

#126 Fix : AudioError
  MarstoEarth/Assets/Scenes/InGameSceneUIPractice.unity
  MarstoEarth/Assets/Scenes/InGameSceneUIPractice.unity.meta
  MarstoEarth/Assets/Scripts/Loading/LoadingScene.cs
  MarstoEarth/Assets/Scripts/Managers/AudioManager.cs
  MarstoEarth/Assets/Scripts/Managers/UIManager.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardInfo.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardUIControll.cs
  MarstoEarth/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#133 Fix : Loading Sequence
  MarstoEarth/Assets/Prefabs/Map/SFRoom/SFGateWall.prefab
  MarstoEarth/Assets/Scripts/Controller/Path/PathController.cs
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Managers/InGameManager.cs
  MarstoEarth/Assets/Scripts/Managers/MapManager.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
Labels: Refactor

#136 121 audio error fix
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/SpeedUp.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/aegisShield.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/blackHole.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/chargeShot.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/distortion.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/fire.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/gardian.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/heal.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/hyperion.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/landMine.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/parryingKick.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/plasma.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/powerUP.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/stun.png
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scenes/InGameSceneUIPractice.unity
  MarstoEarth/Assets/Scenes/InGameSceneUIPractice.unity.meta
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardUIControll.cs
Labels: enhancement

#137 Develop
  MarstoEarth/Assets/Prefabs/Map/SFRoom/SFGateWall.prefab
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/SpeedUp.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/aegisShield.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/blackHole.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/chargeShot.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/distortion.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/fire.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/gardian.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/heal.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/hyperion.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/landMine.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/parryingKick.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/plasma.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/powerUP.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/stun.png
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scenes/InGameSceneUIPractice.unity
  MarstoEarth/Assets/Scenes/InGameSceneUIPractice.unity.meta
  MarstoEarth/Assets/Scenes/LoadingScene.unity
  MarstoEarth/Assets/Scripts/Controller/Path/PathController.cs
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Managers/InGameManager.cs
  MarstoEarth/Assets/Scripts/Managers/MapManager.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardUIControll.cs
Labels: enhancement, Module Structure

#140 Feature/131 map generating refactor 2
  MarstoEarth/Assets/Scenes/InGameScene MJ.unity
  MarstoEarth/Assets/Scenes/InGameScene MJ.unity.meta
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scripts/Controller/Path/PathController.cs
  MarstoEarth/Assets/Scripts/Generators/MapGenerator.cs
  MarstoEarth/Assets/Scripts/Generators/NodeGenerator.cs
  MarstoEarth/Assets/Scripts/Infos/MapInfo.cs
  MarstoEarth/Assets/Scripts/Loading/LoadingScene.cs
  MarstoEarth/Assets/Scripts/Managers/MapManager.cs
  MarstoEarth/Assets/Scripts/Managers/SingleTon.cs
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
  MarstoEarth/Assets/Scripts/Managers/UIManager.cs
Labels: enhancement, Refactor

#151 143 cardui sequence with stat
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/gamename.png
  MarstoEarth/Assets/Resources/Sprites/SkillIcons/gamename.png.meta
  MarstoEarth/Assets/Resources/Sprites/gameBanner.png
  MarstoEarth/Assets/Resources/Sprites/gameBanner.png.meta
  MarstoEarth/Assets/Scenes/OutGameScene.unity
  MarstoEarth/Assets/Scripts/Managers/InGameManager.cs
  MarstoEarth/Assets/Scripts/Managers/OutGameManager.cs
  MarstoEarth/Assets/Scripts/Managers/OutGameUIManager.cs
  MarstoEarth/Assets/Scripts/Managers/OutGameUIManager.cs.meta
  MarstoEarth/Assets/Scripts/Managers/SpawnManager.cs
  MarstoEarth/Assets/Scripts/OutGames.meta
  MarstoEarth/Assets/Scripts/OutGames/GameExplainUI.cs
  MarstoEarth/Assets/Scripts/OutGames/GameExplainUI.cs.meta
  MarstoEarth/Assets/Scripts/OutGames/OutGameSettingUI.cs
  MarstoEarth/Assets/Scripts/OutGames/OutGameSettingUI.cs.meta
  MarstoEarth/Assets/Scripts/OutGames/ReportCheckUI.cs
  MarstoEarth/Assets/Scripts/OutGames/ReportCheckUI.cs.meta
  MarstoEarth/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#161 159 outgamesystem UI json
  MarstoEarth/Assets/ClearData.json
  MarstoEarth/Assets/ClearData.json.meta
  MarstoEarth/Assets/Plugins.meta
  MarstoEarth/Assets/Plugins/SimpleJSON.cs
  MarstoEarth/Assets/Plugins/SimpleJSON.cs.meta
  MarstoEarth/Assets/Plugins/SimpleJSONBinary.cs
  MarstoEarth/Assets/Plugins/SimpleJSONBinary.cs.meta
  MarstoEarth/Assets/Plugins/SimpleJSONDotNetTypes.cs
  MarstoEarth/Assets/Plugins/SimpleJSONDotNetTypes.cs.meta
  MarstoEarth/Assets/Plugins/SimpleJSONUnity.cs
  MarstoEarth/Assets/Plugins/SimpleJSONUnity.cs.meta
  MarstoEarth/Assets/Prefabs/UI/contents.prefab
  MarstoEarth/Assets/Prefabs/UI/contents.prefab.meta
  MarstoEarth/Assets/Resources/Sprites/BGImage/sampleImage_1.png
  MarstoEarth/Assets/Resources/Sprites/BGImage/sampleImage_1.png.meta
  MarstoEarth/Assets/Resources/Sprites/BGImage/sampleImage_2.png
  MarstoEarth/Assets/Resources/Sprites/BGImage/sampleImage_2.png.meta
  MarstoEarth/Assets/Resources/Sprites/BGImage/sampleImage_3.png
  MarstoEarth/Assets/Resources/Sprites/BGImage/sampleImage_3.png.meta
  MarstoEarth/Assets/Scenes/OutGameScene.unity
  MarstoEarth/Assets/Scripts/OutGames/GameExplainUI.cs
  MarstoEarth/Assets/Scripts/OutGames/ReportCheckUI.cs
  MarstoEarth/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#172 163 card reinforce system
  MarstoEarth/Assets/Animations/Card/ReinforceCardUI.anim
  MarstoEarth/Assets/Animations/Card/ReinforceCardUI.controller
  MarstoEarth/Assets/Scenes/InGameScene.unity
  MarstoEarth/Assets/Scripts/Managers/InGameManager.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/CardInfo.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/ReinforceInfo.cs
  MarstoEarth/Assets/Scripts/UI/InGame/CardSystem/ReinforceInfo.cs.meta
  MarstoEarth/Assets/Scripts/UI/InGame/Combat/CombatUI.cs
Labels: enhancement

#178 175 audiomanager static with titlescene
  MarstoEarth/Assets/Scenes/OutGameScene.unity
  MarstoEarth/Assets/Scripts/Managers/AudioManager.cs
  MarstoEarth/Assets/Scripts/OutGames/OutGameSettingUI.cs
Labels: enhancement

#187 Add : OutGameTitle
  MarstoEarth/Assets/Record/202305310845.json
  MarstoEarth/Assets/Record/202305310845.json.meta
  MarstoEarth/Assets/Resources/Sprites/gameTitle.png
  MarstoEarth/Assets/Resources/Sprites/gameTitle2.png
  MarstoEarth/Assets/Resources/Sprites/gameTitle2.png.meta
  MarstoEarth/Assets/Resources/Sprites/gameTitleName.png
  MarstoEarth/Assets/Resources/Sprites/gameTitleName.png.meta
  MarstoEarth/Assets/Scenes/OutGameScene.unity
Labels: enhancement
